{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a4ec3f9a_4fa7658e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1121838
      },
      "writtenOn": "2022-12-01T00:35:38Z",
      "side": 1,
      "message": "Will fix lint error in follow up CL",
      "revId": "615cf7950b96c641ed5133fb17595e813552aaed",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}