{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "4446e7c8_783cc005",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1121838
      },
      "writtenOn": "2022-12-01T00:34:32Z",
      "side": 1,
      "message": "Will fix lint error in follow up CLs",
      "revId": "b8cce16c5503239a6c482197903984c38388cd1e",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}